---
title: "Species"
---

**Recommended citation:**

------------------------------------------------------------------------

## Amphibians

Taxonomic group summary

## Birds

add text

### Terrestrial

Taxonomic group summary

### Estuarine

Estuary birds

## Fish

add text

### Inland aquatic

Taxonomic group summary - Freshwater fish

### Estuarine

Estuary fish

## Invertebrates

### Overview of invetebrate groups assessed to date

### Bees

Taxonomic group summary page

### Branchiopoda

Taxonomic group summary - Large Branchiopoda

### Butterflies

Taxonomic group summary

### Crabs

Taxonomic group summary

### Dragonflies

Taxonomic group summary

### Mollusca

#### Terrestrial

Taxonomic group summary

#### Inland aquatic

### Spiders

Taxonomic group summary

### Estuary invertebrates

Taxonomic group summary 

## Mammals

### Terrestrial

Taxonomic group summary

### Inland aquatic

add text

### Marine

add text

## Plants

Taxonomic group summary

## Reptiles

Taxonomic group summary